### ISSUE TITLE
Hex Intensity

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#102]
How do i lower the intensity of Hex or any WildRigMulti Algo?
22 is causing too many rejects
![hex intensity](https://user-images.githubusercontent.com/30805282/57974488-eff68580-7986-11e9-8194-9120ac1c7998.JPG)

**Comment by yuzi-co** [comment]
You can add a section to Config/MinerParameters.json :

```
"A-WildRigMulti-0.16.5": {
    "Hex": "your custom params",
    "SomeOtherAlgo": "custom params"
}
```

**Comment by Imaminer** [comment]
Thanks!
