### ISSUE TITLE
Cant add blake2b-btcc to config

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#107]
Algorithms_AMD = Lyra2v3,X16r,X16rt,X16s,X17,X20r,X21s,X22i,blake2b-btcc

All work except blake2b-btcc

If I kill this part of config 
;Algorithms_AMD = Lyra2v3,X16r,X16rt,X16s,X17,X20r,X21s,X22i,blake2b-btcc
then blake2b-btcc will benchmark and mine.

Thanks

**Comment by yuzi-co** [comment]
try to put it as blake2bbtcc (no dash)

**Comment by Imaminer** [comment]
Tried that and did not work. 
Also tried Blake2bBTCC (exactly as it's spelled in WildRig).
Really want to use this algo without having to enable everything.

**Comment by Imaminer** [comment]
Well I have tried every possible combinations of spellings, quotes, etc and none work.
I think its just not in your code to recognize this algo in this part of the config.

**Comment by yuzi-co** [comment]
on which pool you have that one?
i will check it

**Comment by Imaminer** [comment]
zergpool

**Comment by yuzi-co** [comment]
I have no idea how it works for you without Algos line at all. It should not. There is no mapping.

I added mapping now to algos.json, and it should work (try adding Blake2bBTCC)

**Comment by Imaminer** [comment]
Excellent.
Thank you for taking the time to fix this.
![working](https://user-images.githubusercontent.com/30805282/61549883-2dc36900-aa1f-11e9-8bf8-fc907d774328.JPG)
