### ISSUE TITLE
How does ZergPool work with Dubai?

### ISSUE THREAD

**Issue by yellow-dragon** [yuzi-co/Forager#112]
My installation steps are as follows:
Step 1: add to Config.ini

> Wallet_DBIX = 0x2280ac4bb2e7484b9276ef8063abfdbee48cd9a7

Step 2: edit AutoStart Example - One coin manual:

> set Mode=Manual
> set Pools=ZergPool
> set Coins=Dubai

but not work, it is error:

> WARNING: NO POOLS! Retry in 30 seconds
> WARNING: If you are mining on anonymous pool without exchage, like YIIMP, NANOPOOL or similar, you must set wallet for
> at least one pool coin in config.ini

I have already added a Dubai wallet, also tested many other wallets => NOT WORK
Please fix it, thanks

**Comment by yellow-dragon** [comment]
If I edit 

> set Pools=ZergPool 

to 

> set Pools=ZergPoolCoins

I see error:
> Key cannot be null.
> Parameter name: key
> At D:\Forager-master\Pools\ZergPoolCoins.ps1:89 char:97
> + ... '24h_btc_shared' -ne $null) { [decimal]$Coin.'24h_btc_shared' } else  ...
> +                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], ArgumentNullException
>     + FullyQualifiedErrorId : System.ArgumentNullException

How to fix it?

**Comment by yuzi-co** [comment]
I will check it, thanks for the report

**Comment by yuzi-co** [comment]
should be fixed in latest git version

If you use the zip release, you can fetch "Pools/ZergPoolCoins.ps1" and "Include.psm1" from the git and put them manually in your install

"set Pools=ZergPoolCoins" is the correct way if you want to mine a single coin

**Comment by yellow-dragon** [comment]
It is working, thanks
