### ISSUE TITLE
Windows 10 - Multi-Desktop donation stall

### ISSUE THREAD

**Issue by rigking** [yuzi-co/Forager#113]
I just got Crooked out of almost a who day of hashing!!!

Using the multi-desktop feature in windows, with Forager running on the second desktop, to reduce the mining windows from pulling focus.

The software stalled in 'DONATION MODE'

I have almost an entire day of "donating"

[FUCK ME.txt](https://github.com/yuzi-co/Forager/files/5235880/FUCK.ME.txt)

**Comment by yuzi-co** [comment]
Sorry to hear, very strange...
Was it already in donation mode when you switched desktops?
Can you provide the forager log as well?

**Comment by rigking** [comment]
This is all that is in the log file ( full thing is 60MB )

the only entry is the final entry, when I saw that the donate time was hung

I have never notice this problem before, I have been using the second desktop for a while now.

The only thing I can recall is I was turning off my AMD card to game

I switched to desktop 2 to turn off AMD, which I have done many time before; difference being that it was during the donation interval.

pressed zero to stop my AMD card.
Forager began 'cycling' (window reset and began with the green font)
at this point I switched back to desktop 1
and went about my gaming

and I believe this time I, again, forgot to re-enable my AMD card ( maybe a future feature "disable card for _defined in config_")

the next time I went back to disable AMD card again, saw the that the donation interval still had 244, and as I watched did not tick down.

at which point I quit

unfortunately I don't know an exact time line: BUT

I am almost certain that at this point I started it again, I decided to let the interval run (because maybe I just HAPPENED to be seeing another donate interval) and upon completion of the 240 seconds, it started another donate interval at which point I quit

the final entry in this log (this is the bottom portion of that 60MB log file); Is me opening forager and it starting on another donation interval, cluing me into the fact that it has probably been looping donations for 16+ hours

I then quit forager
closed the ethlargement window
- all this interaction with forager was done with desktop 2 (opened with a desktop icon[both desktops are exact copies]) -

switched back to desktop 1
posted outrage in some message boards -sry-
then opened forager
and everything has been running normal since

[Forager ERROR.txt](https://github.com/yuzi-co/Forager/files/5236776/Forager.ERROR.txt)

here is a long form
[forager-20200908-173023 Last Day.zip](https://github.com/yuzi-co/Forager/files/5237073/forager-20200908-173023.Last.Day.zip)

**Comment by yuzi-co** [comment]
One possible explanation I have, is QuickEdit mode in windows.
It's on by default (starting with windows 10) and allows you to select a portion of text in console and blocks whatever is running there while selection is active.

If you select something in Forager window (can happen from a single click on the window), Forager blocked and whatever is running, will continue running forever.

Also, in that case you will find a large time gap in the Forager log, since it can't do anything.
Like this part in the log you posted (unless you have edited it):
```
   01:55:49.98	Debug	Interval for pool NiceHash is 900
   01:55:49.98	Debug	Interval for pool Zpool is 900
   01:55:49.98	Debug	Interval for pool NiceHash is 900
   01:55:49.98	Info	Next interval: 900
-> 01:55:52.03	Debug	[{"Group":"AMD","Algorithm":"Ethash","Coin":"Ethash","Miner":"A-ClayDual-15.0","LocalSpeed":"","Shares":"","PLim":{},"Watt":null,"CpuLoad":"0.22","mbtcDay":"0.00000","RevDay":"0.00","ProfitDay":"0.00","Pool":"NiceHash-US"},{"Group":"NVIDIA","Algorithm":"Ethash","Coin":"Ethash","Miner":"N-ClayDual-15.0","LocalSpeed":"","Shares":"","PLim":{},"Watt":null,"CpuLoad":"0.40","mbtcDay":"0.00000","RevDay":"0.00","ProfitDay":"0.00","Pool":"NiceHash-US"},{"Group":"CPU","Algorithm":"Yescrypt|t6*","Coin":"Yescrypt","Miner":"C-CpuMinerOpt-3.12.7","LocalSpeed":"3.721 kh","Shares":"1249/0","PLim":{},"Watt":null,"CpuLoad":"5.57","mbtcDay":"0.03153","RevDay":"0.33","ProfitDay":"0.33","Pool":"Zpool-US"}]
-> 17:28:56.70	Info	Toggle Device group 0
   17:28:56.70	Debug	Interval ends by time: 900
   17:28:56.79	Debug	Config File: {
```

A quick guide how to disable it (not written by me, but explains how to prevent it):
https://www.statmodel.com/download/QuickEdit.pdf


edit:
It's also possible that this is something related specifically to virtual desktops. I never tested it, but it's possible that there is something unexpected

**Comment by yuzi-co** [comment]
Another entry that I see in the full log, in addition to the previous one:
```
   02:20:16.29	Info	Current best: CPU/C-SRBMiner-Multi-0.4.2/Yescrypt/t6/PL0
   02:20:16.29	Info	Next interval: 41.2848510000001680
-> 02:20:17.35	Debug	[{"Group":"NVIDIA","Algorithm":"Ethash","Coin":"Ethash","Miner":"N-ClayDual-15.0","LocalSpeed":"","Shares":"","PLim":{},"Watt":null,"CpuLoad":"0.87","mbtcDay":"0.00000","RevDay":"0.00","ProfitDay":"0.00","Pool":"NiceHash-US"},{"Group":"CPU","Algorithm":"Yescrypt|t6","Coin":"Yescrypt","Miner":"C-SRBMiner-Multi-0.4.2","LocalSpeed":"3.798 kh","Shares":"67/1","PLim":{},"Watt":null,"CpuLoad":"5.80","mbtcDay":"0.03703","RevDay":"0.39","ProfitDay":"0.39","Pool":"ZergPool-US"}]
-> 15:58:46.27	Info	Toggle Device group 0
   15:58:46.28	Debug	Interval ends by time: 41.2848510000001680
```

**Comment by rigking** [comment]
damn, yeah could have been that.

wouldn't be the first time *facepalm*

just the first time it happened during donate.
