### ISSUE TITLE
Automatic overclocking (or underclocking) optimization through Afterburner?

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#14]
First of all, great job with integrating the miner with Afterburner!

It got me thinking, it would be great if the algorithm could change the core clock and the memory clock in order to find the profitability sweet-spot. I was thinking of something like setting the lower bound, the upper bound, and step size, so that the user can constrain the parameters to be within some stable range.

Incidentally, maybe it would be a good idea to do the same with the power limits. For example, if I want to use all the power limits from 50% to 150% in steps of 5%, it would be much easier to set it with those 3 parameters (50,150,5), instead of writing everything (50, 55, ... , 95, 100, 105, ... ,145 150). I assume that most people use power limits like this anyway.

**Comment by yuzi-co** [comment]
closing
