### ISSUE TITLE
UtilizationMem division by zero

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#17]
Include.ps1 at line 237:

`UtilizationMem    = [int]($($CardData | Where-Object SrcName -match "^(GPU\d* )?memory usage").Data / $($CardData | Where-Object SrcName -match "^(GPU\d* )?memory usage").MaxLimit * 100)`

This often results in division by zero. I managed to fix it by changing it to
`UtilizationMem    = [float]($($CardData | Where-Object SrcName -match "^(GPU\d* )?memory usage").Data / [float]$($CardData | Where-Object SrcName -match "^(GPU\d* )?memory usage").MaxLimit * 100 + 0.001)`,

but surely there must be a better way.

**Comment by yuzi-co** [comment]
fixed )
