### ISSUE TITLE
Out of memory errors...

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#26]
I keep getting these messages with the newest version and nothing works. Afterburner on or off, ETHlargementPill on or off, it doesn't matter. The entire system freezes. Tell me if you need more info.

Running startup script threw an error: Exception of type 'System.OutOfMemoryException' was thrown..
    + CategoryInfo          : OpenError: (localhost:String) [], RemoteException
    + FullyQualifiedErrorId : PSSessionStateBroken

[localhost] The background process reported an error with the following message: W i n d o w s   P o w e r S h e l l   t e r m i n a t e d   w i t h   t h e   f o l l o w i n g
 e r r o r :   .
    + CategoryInfo          : OpenError: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : 2100,PSSessionStateBroken

**Comment by VukaKun** [comment]
P.S. Not sure why, but now it's working, I'm not sure how to reproduce the right circumstances...

**Comment by yuzi-co** [comment]
I'm guessing that this was a system issue unrelated to Forager
Do you have the log from the problematic execution(s)?

**Comment by VukaKun** [comment]
Could be, unfortunately, I don't have the logs because I wiped everything before trying again, but they weren't detailed anyway.

However, that might be the reason why it got fixed. Usually, I just update the files as they're updated here, but when I deleted Stats and Bin, everything was fine again.

**Comment by VukaKun** [comment]
Ok, so it happened again. Here's the log:
[2018-05-18_00-03-09.txt](https://github.com/yuzi-co/Forager/files/2014871/2018-05-18_00-03-09.txt)

**Comment by VukaKun** [comment]
And here's the third kind of error that I got... 
![err1](https://user-images.githubusercontent.com/27901969/40206344-e2f7172c-5a2f-11e8-808b-376d2d06093b.png)
And it seems to be working now all of a sudden, but I didn't do anything.

P.S. My paging file is 16 GB large, it's more than enough, maybe it's some kind of a memory leak?

**Comment by yuzi-co** [comment]
Now it hit me... for xmr-stak (amd and nvidia) I cant create gpu groups automatically, they detect it automatically
So both instances probably mine on both cards. Few workarounds to try:
1. Disable xmr-stak and xmr-stak-aeon
2. You can edit 750Ti-CryptoNightV7.txt and 1080Ti-CryptoNightV7.txt in xmr-stak folder after they are initially created to keep only the relevant card
3. Try with 1 group for nvidia cards

I hope this is it and I need to add this to the notes...

**Comment by VukaKun** [comment]
I suspected so myself and it seems to be working. Glad to hear that we came to the same solution! My solution was the 2nd one that you mentioned, works perfectly.

**Comment by yuzi-co** [comment]
Excellent. Closing this :)
