### ISSUE TITLE
MyPools

### ISSUE THREAD

**Issue by toshkov02** [yuzi-co/Forager#27]
Tell me, please, about MyPools.ps. What is it?

**Comment by yuzi-co** [comment]
my personal pools
used also as an example of how to add custom pools

**Comment by yuzi-co** [comment]
of course, they are real pools

you will need to use manual mode, because there is no profit estimations

**Comment by yuzi-co** [comment]
Кстати, ты случаем не по говоришь по русски? )

**Comment by toshkov02** [comment]
В 100 раз лучше английского)))

**Comment by VukaKun** [comment]
Привет из Хорватии, славянские братья! :)

**Comment by toshkov02** [comment]
Привет брат из Хорватии. Я из России)

**Comment by yuzi-co** [comment]
Закрываю )
