### ISSUE TITLE
No Pools...

### ISSUE THREAD

**Issue by david0815** [yuzi-co/Forager#28]
I have a problem since version 1.4:
with more than one selected pool I get error message "No Pools ....", with only a select pool it works correctly.
Win 10 , NVIDIA 1080,1060, clean Install, clean config.ini

**Comment by yuzi-co** [comment]
Submitted a fix to master branch

If you always start same pools, you can modify AutoStart.bat to suit your needs and always run it without manually selecting

**Comment by david0815** [comment]
thank you, it works. its a problem with the start.bat

**Comment by david0815** [comment]
You are FAST. Great Support !
