### ISSUE TITLE
Miner suddenly doesn't even start

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#29]
So, out of nowhere, when I start the miner, I get to this point...

```
Press Enter to continue...: 
Transcript started, output file is .\Logs\2018-05-27_18-35-28.txt
Transcript stopped, output file is G:\Desktop\Forager\Logs\2018-05-27_18-35-28.txt
```

...and then nothing happens. I tried purging Cache and Logs, restarting the PC, but nothing happens.

This is the entire log:

```
**********************
Windows PowerShell transcript start
Start time: 20180527183630
Username: TSUNKUNPC\TsunKun
RunAs User: TSUNKUNPC\TsunKun
Configuration Name: 
Machine: TSUNKUNPC (Microsoft Windows NT 10.0.16299.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -command & .\Miner.ps1
Process ID: 7016
PSVersion: 5.1.16299.15
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.15
BuildVersion: 10.0.16299.15
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2018-05-27_18-36-30.txt
**********************
Windows PowerShell transcript end
End time: 20180527183630
**********************
05/27/2018 18:36:30...... Forager v1.6

```

**Comment by yuzi-co** [comment]
very strange
what are the options you select in the menu?

**Comment by VukaKun** [comment]
Yup, strange. It's the same whatever I select in the menu, Auto/Auto24/Manual, no matter which pool or algorithm, it's the same.

**Comment by yuzi-co** [comment]
I have reworked the logging, try with the new version from master
If it persists, I will probably have more info to work with

Also, I had somewhat similar experience with an antivirus, not sure if its the case though

**Comment by VukaKun** [comment]
Yeah, it seems to be working fine now, everything starts normally. I'm almost certain that it wasn't an antivirus in my case, btw.
