### ISSUE TITLE
A-XMR-Stak-Aeon-2.4.7: Parameter Unknown

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#31]
Parameter unknown '#NoSSL#-o#NoSSL#'
Press any key to exit.

**Comment by yuzi-co** [comment]
It's a miner file from an older version

I made an update May 19th that changed the #NoSSL# params

**Comment by eMTee72** [comment]
Indeed, that miner doesn't exist anymore within the current ZIP. Sorry, should have been able to figure that one out myself!

It's hard to keep up with all the changes you make: new entries in the config.txt, miners get outdated / updated / fixed, etc... still haven't figured out what the best way is to cope with all these changes (in-place upgrade? Clean install? …). On one end I want to keep the downtime as small as possible (including benchmarking), on the other end a new miner may be a new opportunity.

Anyway… I really appreciate all the time and effort you put in this!
