### ISSUE TITLE
Excavator won't mine CryptoNightV7

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#32]
It seems like _nhmp.eu.nicehash.com_ server doesn't recognize **Cryptonightv7** as a valid algorithm. Here's the detailed log from **Excavator-1.5.4a**:
[log](https://github.com/yuzi-co/Forager/files/2065184/GitHub.txt)

**Comment by yuzi-co** [comment]
can you please change in the miner file  line 20 to "cryptonightv7" to "cryptonightV7" (capital V),
and see if that fixes the issue?

I believe that this actually belongs in Excavator issues (https://github.com/nicehash/excavator/issues), but if that helps, I'll fix that

**Comment by VukaKun** [comment]
lol, that actually worked! :)

If the capitalization of "V" fixed the issue, isn't the issue on Forager's side? But yeah, it's an easy fix.

**Comment by yuzi-co** [comment]
it's an idiotic thing on nicehash part to require case sensitive algo
