### ISSUE TITLE
Amd Api, cant detect hashrate

### ISSUE THREAD

**Issue by Krigmao** [yuzi-co/Forager#33]
Some of miner works perfect, but it cant detect any hash rate, it runs forever the benchmark

![api_fail](https://user-images.githubusercontent.com/30592403/40884136-a5c7f92a-670e-11e8-9faf-54c9868c9aaf.jpg)

**Comment by yuzi-co** [comment]
Please attach log file

**Comment by Krigmao** [comment]
[2018-06-03_08-17-15.log](https://github.com/yuzi-co/Forager/files/2065778/2018-06-03_08-17-15.log)
i just delete some "miner".json file, to see what happend

**Comment by Krigmao** [comment]
Thanks, now it works
