### ISSUE TITLE
 Stratum connect timeout, failover...

### ISSUE THREAD

**Issue by toshkov02** [yuzi-co/Forager#37]
Привет.
Можешь добавить возможность временного отключения добычи при сообщениях " Stratum connect timeout, failover..."?
Например, сегодня в 11:40 пул Nicehash при использовании алгоритма Lyra2z в N-Coolminer выдавал такую ошибку во время бенчмарка. Из-за этого бенчмарк не проходил дальше.
Пришлось закомментировать использование этого алгоритма в N-Coolminer.
В Config.ini выставление параметра WatchdogHashrate = 40 не помогло. У меня WatchdogExcludeAlgos = X16r.

**Comment by yuzi-co** [comment]
WatchogHasrate работает только после того как бенчмаркинг пройден. Что касается Nicehash, некоторые алгоритмы отключают тебя если нету на них заказов (я поэтому отключил HOdl на CPU). Попробуй пробенчить на другом пуле

**Comment by toshkov02** [comment]
Как побенчить на другом пуле? 
Заметил, что N-CcminerSTS-2.2.6R на том же алгоритме Lyra2z подрыгался, получал ошибку и отвалился. В логах Detected miner error N-CcminerSTS-2.2.6R/Lyra2z. Бенчмарк пошёл дальше. N-Coolminer же не отваливается и продолжает упорно стучаться на пул найса. Может всё-таки добавишь такую проверку на "Stratum connect timeout, failover..."? 
Может случиться, что найс захочет добавить новый алгоритм. Майнеры увидят, начнут делать бенчмарк и, в случае таймаута как сейчас, фермы будут простаивать пытаясь завершить бенчмарк.

**Comment by yuzi-co** [comment]
Чтобы пробенчить на другом пуле просто запусти на другом пуле где есть Lyra2z - например MiningPoolHub, Zpool, ZergPool
Если запускаешь на несколько, то уберу NH из списка, а после бенчмарка верни

Сам майнер должен закрываться когда есть ошибка. В Coolminer включена эта опция, но возможно не работает (я не могу проверить, у меня нет железа NVIDIA).
Я не буду делать проверку на "Stratum connect timeout", потому что (1) у всех майнеров ошибки выглядят по разному и (2) я не обрабатываю текст сообщений.  Это снижает производительность, усложняет разработку и не поддерживается всеми майнерами.

**Comment by yuzi-co** [comment]
Вышла новая версия coolMiner. Они пофиксили проблему с NH
