### ISSUE TITLE
AutoStartAhash.bat does not work

### ISSUE THREAD

**Issue by jrafaelmdo** [yuzi-co/Forager#4]
Hello,

I wanted to give your fork a go, downloaded latest master and AutoStartAhash.bat does not work

Using Start.bat and selecting Automatic -> Ahashpool works just fine.

Thanks

**Comment by yuzi-co** [comment]
Any errors?
Which windows version are you using?

**Comment by jrafaelmdo** [comment]
![capture1](https://user-images.githubusercontent.com/35340377/37676197-24169b18-2c6f-11e8-9c21-ae532b46632c.PNG)

**Comment by jrafaelmdo** [comment]
![capture2](https://user-images.githubusercontent.com/35340377/37676203-279726b8-2c6f-11e8-88f1-161110681b57.PNG)

**Comment by jrafaelmdo** [comment]
Windows 10 x64
Powershell 6.0.2

**Comment by yuzi-co** [comment]
Do you have BTC wallet configured in config.txt ?
Both errors show that you don't have a BTC wallet configured (and it is required on Ahash)
I'll add checks to prevent the errors

**Comment by jrafaelmdo** [comment]
I do have my BTC wallet in the config file.

I have no problems running megaminer from the start.bat only fails when I try to use the AutoStartAhash.bat file.

**Comment by yuzi-co** [comment]
I have made a few changes processing config file
Can you please set "@@DebugLog=Enabled" and post here a log from latest version?
You can remove sensitive data before posting (real wallets/api keys)
