### ISSUE TITLE
Watt 0W

### ISSUE THREAD

**Issue by toshkov02** [yuzi-co/Forager#41]
Привет.
У меня на Radeon RX 580 значение Watt всегда 0W. В (C)urrent Power тоже 0W. Проблема появилась где-то полтора-два месяца назад.
Включение Afterburner не помогло.
Load, Temp, Fan, Clock и ClkMem значения показывают.

**Comment by yuzi-co** [comment]
Пришли пожалуйста результат AfterburnerRepot

**Comment by toshkov02** [comment]
[log.log](https://github.com/yuzi-co/Forager/files/2101620/log.log)

**Comment by yuzi-co** [comment]
В нем нету данных о потреблении (GPUx power), возможно в Afterburner отключено что то...
Я проверю почему без AB нету данных. Должно показывать...

**Comment by toshkov02** [comment]
Всё включал. Даже версию 4.4.2 ставил. Не помогло. Возможно из-за включённой встроенной видюхи.

**Comment by yuzi-co** [comment]
> Возможно из-за включённой встроенной видюхи

Не должно влиять. Я проверял у себя, показывает потребление и с ней и без неё
А в самом АВ видишь ли потребление?

**Comment by toshkov02** [comment]
В АВ энергопотребления для RX 580 нет.
Есть ферма с двумя NVIDIA 1060 и одной AMD RX 580. Так для 1060 показывает энергопотребление, а для 580 - нет.
Версия PowerShell не влияет, и 5 и 6 версия энергопотребление не показывают.
Закомментирование Afterburner = ENABLED и включение GpuGroupByType в конфиге не помогает.

**Comment by yuzi-co** [comment]
Я пофиксил работу без АВ

**Comment by toshkov02** [comment]
Спасибо. Заработало. Мне теперь надо бенчмарк заново пройти или не обязательно?
Лучший алгоритм выбирается с учётом энергопотребления?
И A-XMRig-2.7.0b выдаёт ошибку: 
```
[2018-06-15 12:00:00] compiling code and initializing GPUs. This will take a while...
[2018-06-15 12:00:01] using non AMD device: Intel(R) Corporation
[2018-06-15 12:00:01] Error CL_DEVICE_NOT_FOUND when calling clGetDeviceIDs for number of devices.
```
Использовался алгоритм CryptoNightHeavy и CryptoNightV7. И там и там ошибка.

**Comment by toshkov02** [comment]
Вылезла ошибка при первом запуске на ферме, где Nvidia 1060 и RX 580 вместе (на ферме, где только RX 580 такой ошибки нет). AB не используется. Раньше такой ошибки не было.
```
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\Users\user\Desktop\min\Megaminer\Include.ps1:17 char:9
+         $PowerDefaultLimit = [int]((& $Command $Arguments) -replace ' ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : ConvertToFinalInvalidCastException

Provided power limit 0.00 W is not a valid power limit which should be between 78.00 W and 182.00 W for GPU 00000000:01:00.0
Terminating early due to previous errors.
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\Users\user\Desktop\min\Megaminer\Include.ps1:17 char:9
+         $PowerDefaultLimit = [int]((& $Command $Arguments) -replace ' ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : ConvertToFinalInvalidCastException

Provided power limit 0.00 W is not a valid power limit which should be between 60.00 W and 140.00 W for GPU 00000000:02:00.0
Terminating early due to previous errors.
```

**Comment by yuzi-co** [comment]
> Мне теперь надо бенчмарк заново пройти или не обязательно?
Лучший алгоритм выбирается с учётом энергопотребления?

Да, выбирается с учетом энергопотребления. Но, если не используется АВ, то потребление для AMD практически всегда максимально возможное, а не реальное, поэтому в принципе не обязательно. Изменится только Estimated profit

**Comment by yuzi-co** [comment]
Ошибку с NVidia думаю что пофиксил

XMrig смогу проверить позже

**Comment by toshkov02** [comment]
Не пофиксил(
```
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\Users\user\Desktop\min\Megaminer\Include.ps1:17 char:9
+         $PowerDefaultLimit = [int](((& $Command $Arguments) -replace  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : ConvertToFinalInvalidCastException

Provided power limit 0.00 W is not a valid power limit which should be between 78.00 W and 182.00 W for GPU 00000000:01:00.0
Terminating early due to previous errors.
Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Int32".
At C:\Users\user\Desktop\min\Megaminer\Include.ps1:17 char:9
+         $PowerDefaultLimit = [int](((& $Command $Arguments) -replace  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [], RuntimeException
+ FullyQualifiedErrorId : ConvertToFinalInvalidCastException

Provided power limit 0.00 W is not a valid power limit which should be between 60.00 W and 140.00 W for GPU 00000000:02:00.0
Terminating early due to previous errors.
```

**Comment by toshkov02** [comment]
Не буду плодить issue)
A-Sgminer4ward-x16-1.0 требует для работы библиотеку MSVCR100.dll

**Comment by toshkov02** [comment]
N-CryptoDredge-0.4.0 хоть и обновился, но не работает. Изменилось только то, что при запуске показывает начальную картинку CRYPTODREDGE в рамке, а потом тишина. Это я так, тебе для информации.

**Comment by yuzi-co** [comment]
> Не пофиксил(

Да, пропустил еще одно место. Сейчас вроде всё

> A-Sgminer4ward-x16-1.0 требует для работы библиотеку MSVCR100.dll

Добавил Prerequisites

> N-CryptoDredge-0.4.0 хоть и обновился, но не работает

Я так и думал. Ждем API

**Comment by yuzi-co** [comment]
Только если используешь PowerLimits

**Comment by toshkov02** [comment]
Не совсем понятно что в PowerLimits выставлять.
Я правильно понял, что при "PowerLimits": "100,90,80" сначала бэнчмарк на 100%, потом 90%, потом 80%.
Тогда вопрос, а если я хочу завысить параметр PowerLimits до максимума? Или 100% - это и есть максимум?
И как в GpuGroups выбрать все видеокарты в группе "GroupName"?
