### ISSUE TITLE
Column Watt is a percentage with AB enabled, not real wattage?

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#43]
When Afterburner = Enabled (in config), the value under Watt is the % and not the real value.

Example below are for a 1080Ti (250W TDP):
![image](https://user-images.githubusercontent.com/32677058/41588694-bfcc6058-73b2-11e8-88db-fb74d5029f1b.png)

```
Result of Afterburner.bat:

Signature     : 1296123981
Version       : 131072
HeaderSize    : 32
EntryCount    : 44
EntrySize     : 1324
Time          : 1529399622
GpuEntryCount : 1
GpuEntrySize  : 1304




SrcName          SrcUnits LocalizedSrcName LocalizedSrcUnits RecommendedFormat     Data MinLimit MaxLimit Flags        GPU
-------          -------- ---------------- ----------------- -----------------     ---- -------- -------- -----        ---
GPU temperature  °C       GPU temperature  °C                %.0f                    63        0      100  None          0
GPU usage        %        GPU usage        %                 %.0f                    99        0      100  None          0
FB usage         %        FB usage         %                 %.0f                    75        0      100  None          0
VID usage        %        VID usage        %                 %.0f                     0        0      100  None          0
BUS usage        %        BUS usage        %                 %.0f                     0        0      100  None          0
Memory usage     MB       Memory usage     MB                %.0f              2016.121        0     8192  None          0
Core clock       MHz      Core clock       MHz               %.0f                  1898        0     2500  None          0
Memory clock     MHz      Memory clock     MHz               %.0f                  5508        0     7500  None          0
Power            %        Power            %                 %.0f                    99        0      150  None          0
Fan speed        %        Fan speed        %                 %.0f                    86        0      100  None          0
Fan tachometer   RPM      Fan tachometer   RPM               %.0f                  2433        0    10000  None          0
Temp limit                Temp limit                         %.0f                     0        0        1  None          0
Power limit               Power limit                        %.0f                     1        0        1  None          0
Voltage limit             Voltage limit                      %.0f                     0        0        1  None          0
No load limit             No load limit                      %.0f                     0        0        1  None          0
CPU1 temperature °C       CPU1 temperature °C                %.0f                42.875        0      100  None          0
CPU1 usage       %        CPU1 usage       %                 %.0f                   100        0      100  None          0
CPU2 usage       %        CPU2 usage       %                 %.0f                28.125        0      100  None          1
CPU3 usage       %        CPU3 usage       %                 %.0f                   100        0      100  None          2
CPU4 usage       %        CPU4 usage       %                 %.0f               48.4375        0      100  None          3
CPU5 usage       %        CPU5 usage       %                 %.0f                   100        0      100  None          4
CPU6 usage       %        CPU6 usage       %                 %.0f               39.0625        0      100  None          5
CPU7 usage       %        CPU7 usage       %                 %.0f                   100        0      100  None          6
CPU8 usage       %        CPU8 usage       %                 %.0f                  37.5        0      100  None          7
CPU9 usage       %        CPU9 usage       %                 %.0f                   100        0      100  None          8
CPU10 usage      %        CPU10 usage      %                 %.0f               17.1875        0      100  None          9
CPU11 usage      %        CPU11 usage      %                 %.0f                   100        0      100  None         10
CPU12 usage      %        CPU12 usage      %                 %.0f                 31.25        0      100  None         11
CPU usage        %        CPU usage        %                 %.0f              66.79688        0      100  None 4294967295
CPU1 clock       MHz      CPU1 clock       MHz               %.0f                  3400        0     5000  None          0
CPU2 clock       MHz      CPU2 clock       MHz               %.0f                  3400        0     5000  None          1
CPU3 clock       MHz      CPU3 clock       MHz               %.0f                  3400        0     5000  None          2
CPU4 clock       MHz      CPU4 clock       MHz               %.0f                  3400        0     5000  None          3
CPU5 clock       MHz      CPU5 clock       MHz               %.0f                  3400        0     5000  None          4
CPU6 clock       MHz      CPU6 clock       MHz               %.0f                  3400        0     5000  None          5
CPU7 clock       MHz      CPU7 clock       MHz               %.0f                  3400        0     5000  None          6
CPU8 clock       MHz      CPU8 clock       MHz               %.0f                  3400        0     5000  None          7
CPU9 clock       MHz      CPU9 clock       MHz               %.0f                  3400        0     5000  None          8
CPU10 clock      MHz      CPU10 clock      MHz               %.0f                  3400        0     5000  None          9
CPU11 clock      MHz      CPU11 clock      MHz               %.0f                  3400        0     5000  None         10
CPU12 clock      MHz      CPU12 clock      MHz               %.0f                  3400        0     5000  None         11
CPU clock        MHz      CPU clock        MHz               %.0f                  3400        0     5000  None 4294967295
RAM usage        MB       RAM usage        MB                %.0f                  5111        0    16384  None          0
Pagefile usage   MB       Pagefile usage   MB                %.0f                 10865        0    16384  None          0




GpuId     : VEN_10DE&DEV_1B06&SUBSYS_374D1458&REV_A1&BUS_9&DEV_0&FN_0
Family    : GP102-A
Device    : GeForce GTX 1080 Ti
Driver    : 398.11
BIOS      : 86.02.39.00.9d
MemAmount : 0
Index     : 0
```

When commenting out the 'Afterburner = Enabled' line in Config, the real Wattage is shown:
![image](https://user-images.githubusercontent.com/32677058/41589375-a762511a-73b4-11e8-8e42-28617b5ebc91.png)

**Comment by yuzi-co** [comment]
Ok, got it... for NVidia, Power is in % and not Wattage like AMD
I'll work on it

**Comment by eMTee72** [comment]
Thanks!

Which means that all NVIDIA-benchmarks need to run again, I assume? At least when 'AB = Enabled' is being used...

**Comment by yuzi-co** [comment]
> Which means that all NVIDIA-benchmarks need to run again, I assume? At least when 'AB = Enabled' is being used...

Unfortunately yes, otherwise it won't be very accurate

**Comment by eMTee72** [comment]
Only if AB=Enabled was used? Or all NVIDIA benchmarks?

**Comment by yuzi-co** [comment]
Only when AB=Enabled was used for NVIDIA benchmarks (CPU will have correct values)

And I need your help to fix this, since I dont have NVIDIA hardware...

Can you please open powershell in Forager folder, run the following and post here the output?
```
. .\Includes\Afterburner.ps1
$abControl.GpuEntries[0]
```

**Comment by yuzi-co** [comment]
And I think I can make a quick script to fix the benchmarks when I fix the code, to save you time benchmarking )

**Comment by eMTee72** [comment]
Had to change the Execution Policy to be able to run it.

Here is is (for a 1080Ti, currently with "AB=Disabled" and using AB to PL on 70%):
PS D:\yuzi-co\GitHub\Forager> . .\Includes\Afterburner.ps1
$abControl.GpuEntries[0]


Flags                 : FAN_SPEED, CORE_VOLTAGE_BOOST, POWER_LIMIT, CORE_CLOCK_BOOST, MEMORY_CLOCK_BOOST, THERMAL_LIMIT, SYNCHRONIZED_WITH_MASTER
CoreClockCur          : 0
CoreClockMin          : 0
CoreClockMax          : 0
CoreClockDef          : 0
ShaderClockCur        : 0
ShaderClockMin        : 0
ShaderClockMax        : 0
ShaderClockDef        : 0
MemoryClockCur        : 0
MemoryClockMin        : 0
MemoryClockMax        : 0
MemoryClockDef        : 0
FanSpeedCur           : 69
FanFlagsCur           : AUTO
FanSpeedMin           : 25
FanSpeedMax           : 100
FanSpeedDef           : 0
FanFlagsDef           : AUTO
CoreVoltageCur        : 0
CoreVoltageMin        : 0
CoreVoltageMax        : 0
CoreVoltageDef        : 0
MemoryVoltageCur      : 0
MemoryVoltageMin      : 0
MemoryVoltageMax      : 0
MemoryVoltageDef      : 0
AuxVoltageCur         : 0
AuxVoltageMin         : 0
AuxVoltageMax         : 0
AuxVoltageDef         : 0
CoreVoltageBoostCur   : 0
CoreVoltageBoostMin   : 0
CoreVoltageBoostMax   : 100
CoreVoltageBoostDef   : 0
MemoryVoltageBoostCur : 0
MemoryVoltageBoostMin : 0
MemoryVoltageBoostMax : 0
MemoryVoltageBoostDef : 0
AuxVoltageBoostCur    : 0
AuxVoltageBoostMin    : 0
AuxVoltageBoostMax    : 0
AuxVoltageBoostDef    : 0
PowerLimitCur         : 70
PowerLimitMin         : 50
PowerLimitMax         : 150
PowerLimitDef         : 100
CoreClockBoostCur     : 50000
CoreClockBoostMin     : -400000
CoreClockBoostMax     : 1000000
CoreClockBoostDef     : 0
MemoryClockBoostCur   : 500000
MemoryClockBoostMin   : -502296
MemoryClockBoostMax   : 1000000
MemoryClockBoostDef   : 0
ThermalLimitCur       : 70
ThermalLimitMin       : 65
ThermalLimitMax       : 90
ThermalLimitDef       : 84
IsMaster              : True
Index                 : 0

And here for a 1060 (with "AB=Enabled" while Forager is running with PL 70%):

Flags                 : FAN_SPEED, CORE_VOLTAGE_BOOST, POWER_LIMIT, CORE_CLOCK_BOOST, MEMORY_CLOCK_BOOST, THERMAL_LIMIT, SYNCHRONIZED_WITH_MASTER
CoreClockCur          : 0
CoreClockMin          : 0
CoreClockMax          : 0
CoreClockDef          : 0
ShaderClockCur        : 0
ShaderClockMin        : 0
ShaderClockMax        : 0
ShaderClockDef        : 0
MemoryClockCur        : 0
MemoryClockMin        : 0
MemoryClockMax        : 0
MemoryClockDef        : 0
FanSpeedCur           : 55
FanFlagsCur           : AUTO
FanSpeedMin           : 25
FanSpeedMax           : 100
FanSpeedDef           : 0
FanFlagsDef           : AUTO
CoreVoltageCur        : 0
CoreVoltageMin        : 0
CoreVoltageMax        : 0
CoreVoltageDef        : 0
MemoryVoltageCur      : 0
MemoryVoltageMin      : 0
MemoryVoltageMax      : 0
MemoryVoltageDef      : 0
AuxVoltageCur         : 0
AuxVoltageMin         : 0
AuxVoltageMax         : 0
AuxVoltageDef         : 0
CoreVoltageBoostCur   : 0
CoreVoltageBoostMin   : 0
CoreVoltageBoostMax   : 100
CoreVoltageBoostDef   : 0
MemoryVoltageBoostCur : 0
MemoryVoltageBoostMin : 0
MemoryVoltageBoostMax : 0
MemoryVoltageBoostDef : 0
AuxVoltageBoostCur    : 0
AuxVoltageBoostMin    : 0
AuxVoltageBoostMax    : 0
AuxVoltageBoostDef    : 0
PowerLimitCur         : 70
PowerLimitMin         : 50
PowerLimitMax         : 116
PowerLimitDef         : 100
CoreClockBoostCur     : 120000
CoreClockBoostMin     : -400000
CoreClockBoostMax     : 1000000
CoreClockBoostDef     : 0
MemoryClockBoostCur   : 530000
MemoryClockBoostMin   : -502296
MemoryClockBoostMax   : 1000000
MemoryClockBoostDef   : 0
ThermalLimitCur       : 70
ThermalLimitMin       : 60
ThermalLimitMax       : 92
ThermalLimitDef       : 83
IsMaster              : False
Index                 : 0

Need anything else?

**Comment by eMTee72** [comment]
About that 'quick script': don't worry too much about me as I do not have to benchmark a lot of algo's again. Lucky for me, I noticed quickly something was wrong when I was trying the 'AB=Enabled' setting combined with the GPUGroups.

I'm more worried about the incorrect Profits that a lot of people out there are seeing now, thinking that Forager must be doing some magic on their system.   ;-)

**Comment by yuzi-co** [comment]
Thank you!
But, the bad news is that looks like AB doesn't provide any real power consumption for NVIDIA, so I will need to rely on nvidia-smi.
I guess Afterburner should be only enabled for AMD and CPU

**Comment by eMTee72** [comment]
Nvidia-smi indeed shows the correct values (or at least: the values I would expect). But the disadvantage is that it requires elevated rights, which means that whenever you start up Forager, it will for each instance of Nvidia-smi ask for your permissions. Pretty annoying, to be honest!
Thinking one step ahead: if you'll need Nvidia-smi for setting the PL each time a different algo is selected (or when a PL is changed), you basically ask people to stay at their rig all day (or get rid of UAC altogether). Now what will happen if the PL needs to be set in a system with e.g. 8 GPU's?

**Comment by yuzi-co** [comment]
For a dedicated mining rig it would be reasonable to disable UAC
I would just be rolling back to the way Megaminer works.

Now... Does nvidia-smi need UAC approval for information or only for setting powerlimits?

**Comment by yuzi-co** [comment]
If information doesnt require admin, I can work around that...

**Comment by yuzi-co** [comment]
this is the command that runs every time to retrieve info. it shouldn't require admin
`nvidia-smi.exe --query-gpu=gpu_name,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,fan.speed,pstate,clocks.current.graphics,clocks.current.memory,power.max_limit,power.default_limit --format=csv,noheader`

there is no additional nvidia-smi executions if not using powerlimits in Forager

**Comment by eMTee72** [comment]
I ran the above Nvidia-smi from an unelevated command prompt just fine!

**Comment by yuzi-co** [comment]
I changed behavior now to use nvidia-smi for card information and afterburner can still be used to set powerlimits

**Comment by eMTee72** [comment]
Initial tests look fine: Forager is reporting same values as SMI (no surprise there!).  :-)

**Comment by yuzi-co** [comment]
I believe issue resolved. Closing this. )
