### ISSUE TITLE
Suggestion - Add runtime timer to windows console

### ISSUE THREAD

**Issue by jrafaelmdo** [yuzi-co/Forager#44]
Hello,

Thank you for this great miner, can I suggest if possible to add runtime into the title bar, this feature is already implemented in Nemosminer. hopefully its easy to add.

I tried to added myself but just keep breaking the script.

https://github.com/nemosminer/NemosMiner/blob/master/Core-v3.1.ps1

Lines 24 and 101

Thanks

**Comment by yuzi-co** [comment]
Useful enough
Added in master branch ;)

**Comment by yuzi-co** [comment]
Displaying runtime and currently mined coins in the title
