### ISSUE TITLE
No Pools Message

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#45]
Been trying this latest version and cannot get it running. All I ever get is No Pools message.
Is config.ini supposed to be an actual .ini file or or is it supposed to be a .txt file? Well I tried both.
Its acting like it isnt seeing the wallet in the config file.

**Comment by yuzi-co** [comment]
Post the log please

**Comment by Imaminer** [comment]
I see the issue right at the beginning of the log. Cant find config.ini
I have a config.ini (real ini file) and a config.ini (txt file).
Apparently it cannot find either one.
[2018-06-27_08-23-41.log](https://github.com/yuzi-co/Forager/files/2141782/2018-06-27_08-23-41.log)
