### ISSUE TITLE
Asking for MS Visual C++ On every download

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#46]
Couldnt find anything logged so heres a screenshot
On startup and on EVERY download of every miner I have to do this.
Endless....
https://ibb.co/gE0ZFT

**Comment by yuzi-co** [comment]
remove A-Sgminer4ward-x16-1.0.json from Miners folder
its not among the best anyway

i have removed it from master branch

**Comment by Imaminer** [comment]
Thanks that solved the issue.
