### ISSUE TITLE
PowerDefaultLimit does not work

### ISSUE THREAD

**Issue by DrRobotto** [yuzi-co/Forager#47]
This line does not work on my machines because the casting to System.int32 does not work:
$PowerDefaultLimit = [int](((& $Command $Arguments) -replace 'W').Trim())

It resides in the include.ps1

**Comment by yuzi-co** [comment]
can you please run the following command for each device you have (with replace $Device with device id)
`nvidia-smi.exe -i $Device --query-gpu=power.default_limit --format=csv,noheader`

**Comment by DrRobotto** [comment]
I changed the code to:
$xpr=".\includes\nvidia-smi.exe -i "+$Device+" --query-gpu=power.default_limit --format=csv,noheader"  
$PowerDefaultLimit=[int]((invoke-expression $xpr) -replace 'W','')

and it worked.

Your line gives:
C:\Users\DrRobotto\Downloads\Miner\Forager-18.07\Includes>nvidia-smi.exe -i 0 --query-gpu=power.default_limit --format=csv,noheader
180.00 W

**Comment by yuzi-co** [comment]
can you please test if this works on your pc (Resolve-Path added)

```
        $Command = (Resolve-Path -Path '.\includes\nvidia-smi.exe').Path
        $Arguments = @(
            "-i $Device"
            "--query-gpu=power.default_limit"
            "--format=csv,noheader"
        )
        $PowerDefaultLimit = [int](((& $Command $Arguments) -replace 'W').Trim())
```

**Comment by DrRobotto** [comment]
Same problem as before ...
