### ISSUE TITLE
Delosminer hack issue

### ISSUE THREAD

**Issue by arminmacx** [yuzi-co/Forager#48]
As i read on community about delosminer and its been hacking wallet, I just want to know why you still using it in your app?

the link for this matter :
https://discordapp.com/channels/447367713783021598/447376063375605761
https://github.com/nemosminer/NemosMiner/issues/649

**Comment by yuzi-co** [comment]
thank you for bringing this to my attention
now disabled by default

a general warning: never keep wallets on a mining pc, or at least have them password protected!

**Comment by arminmacx** [comment]
im not having any wallet i just read it on those community and then see your app wanted to try it then see you are using delosminer too. :D
