### ISSUE TITLE
Error on N-lolMinerZero-0.37

### ISSUE THREAD

**Issue by DrRobotto** [yuzi-co/Forager#49]
The following miner gives an error on my machines (I deleted the BTC address):
Forager\Bin\N-lolMinerZero-0.37\lolMiner-zero.exe --server equihash192.mine.zergpool.com --port 2144 --user MY_BTC_ADDRESS --pass c=BTC,ID=DESK-8OS_NVIDIA --platform 0 --device 0,1,2,3,4,5 --use-compact-short-stat

It gives: Number of hosts (1) does not match number of worker passwords (2)

Keep up the good work!

**Comment by yuzi-co** [comment]
Ok, probably the comma is processed incorrectly by the miner. I will have to drop the workername for this miner
