### ISSUE TITLE
Latest version error dl file

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#50]
Downloading https://github.com/CryptoGraphics/lyclMiner/releases/download/untagged-95777e4326ae4e5ccdb5/lyclMiner015.zip
WARNING: File hash doesn't match. Removing file.

**Comment by yuzi-co** [comment]
Original file was replaced by the developer (or someone from his account)
This is exactly why I have SHA256 checksum validation

I will review if the new file is safe before updating

Meanwhile attaching original file (you can drop it in Downloads folder)

[lyclMiner015.zip](https://github.com/yuzi-co/Forager/files/2216487/lyclMiner015.zip)


pending author answer on ticket:
https://github.com/CryptoGraphics/lyclMiner/issues/12

**Comment by Imaminer** [comment]
Thanks!
