### ISSUE TITLE
Scrypt Miner

### ISSUE THREAD

**Issue by Imaminer** [yuzi-co/Forager#51]
Hard to believe but lately Zergpool has Scrypt as top paying algo.
Please add a AMD and a NV Scrypt miner.

**Comment by yuzi-co** [comment]
It's very hard to believe that an algo that already has 3 (I believe) generations of ASICS would be profitable on a GPU
Miracles don't happen in mining ;)

**Comment by Imaminer** [comment]
Guess the ASIC's are hitting it hard...
