### ISSUE TITLE
CryptoDredge 0.6 unsave the hashrate

### ISSUE THREAD

**Issue by czjlj** [yuzi-co/Forager#52]
0.6 is more stable than 0.7 but unsave the hashrate file.

**Comment by yuzi-co** [comment]
if you want to use v6, API should be "cryptodredge"

or just use the file from https://raw.githubusercontent.com/yuzi-co/Forager/f9d32b4025a5406bd39d80586c22ba68bb5b13b7/Miners/N-CryptoDredge-0.6.0.json

**Comment by czjlj** [comment]
thank you very much
