### ISSUE TITLE
Question: It is possible to disable power monitoring ?

### ISSUE THREAD

**Issue by jrafaelmdo** [yuzi-co/Forager#55]
Question: It is possible to disable power monitoring ?

If so how you do it, if not can you implement this "feature" ?

Background, for some reason in my systems (nvidia 1070ti, 1060, 1050ti) the constant polling of nvdia-smi running causes a lot of inestability. for example when I use ccminer 2.30 with hmq1725 by itself all cards are stable for as long I let them run, if I close the miner and start forager same algo and miner causes random GPU crashes.

**Comment by yuzi-co** [comment]
I will add the option

**Comment by yuzi-co** [comment]
added option in master branch
