### ISSUE TITLE
N-lolminer-43 Application Has Been Blocked From Accessing Graphics Hardware

### ISSUE THREAD

**Issue by DrRobotto** [yuzi-co/Forager#57]
The above miner gives me "Application Has Been Blocked From Accessing Graphics Hardware"
Every other miner works without any problems ... any thoughts?

**Comment by yuzi-co** [comment]
Frankly no idea, never had this.
And the great google find lots of different stuff like:
Reinstall drivers, lower OC, possible overheating issues, remove NVIDIA experience...

https://www.reddit.com/r/techsupport/comments/3so0uu/updates_nvidia_graphics_driver_stopped/
https://www.reddit.com/user/VVarHawK

Don't know what might help...
