### ISSUE TITLE
No Hashrate Detected for Cryptonote-Node.JS Pools

### ISSUE THREAD

**Issue by flylifeny** [yuzi-co/Forager#68]
Hi @yuzi-co,

Do you have any plans in adding a pool that is on the **cryptonote-node.js pool software**? Or is there one I overlooked? I have a few pools running on that software added to mypools.ps1, and they  mine, however they do not detect a hashrate when mining, so  I cannot run them in auto mode effectively, only manual. If I run on auto, the currencies will basically be at the bottom of the list, or not visible, unless the currency exchange rate is exceptionally high compared to other currencies on the auto-switch list. Even then its near impossible for it to mine because profit is negative.

If you don't plan on adding support, is there any documentation you can point me to that might help me in getting a proper API connection for pools running on cryptonote-node.js?

**Example pools:** 
https://lines.clevery.xyz/
https://pool.bitcoin2.network/

Thanks for your help and the excellent fork! Much appreciated.

**Comment by yuzi-co** [comment]
It's not about hashrate, but about profitability info which those pools don't have
For Auto mode you need to know how much BTC equivalent you get per your hashrate
