### ISSUE TITLE
Lyclminer 0.2.0 released with support for Lyra2v3 for AMD

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#74]
Lyclminer 0.2.0 released with support for Lyra2re3 for amd

Added a Lyra2REv3 support(enabled by default).
Added a configuration option "Algorithm" inside a Connection section.(Choose between Lyra2REv2 and Lyra2REv3).
Updated and improved all asm kernels for Lyra2REv3.
Added a gfx6 asm optimized kernel for GCN 1.0(Pitcairn, Tahiti). Lyra2REv3 and Windows only.
Fixed compile errors with OpenCL 1.2 headers(without OpenCL 2+ support

https://github.com/CryptoGraphics/lyclMiner/releases

**Comment by yuzi-co** [comment]
updated
