### ISSUE TITLE
EquiHash (AMD): incorrect

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#8]
Something seems to be off with EquiHash on NH.
Other algo's (on NH or other pools) seem to be fine...
If one RX570 can generate this, I'm ordering a shipload.   ;-)

Same Algo on NVidia (same pool / different machine) generates more realistic values...

![image](https://user-images.githubusercontent.com/32677058/38744782-0986a4be-3f43-11e8-9e86-6e3ab4b44a43.png)

**Comment by yuzi-co** [comment]
error in api reading :)
should detect speed correctly now
