### ISSUE TITLE
TTminer 2.1.7 speed incorrectly displayed in forager

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#80]
Pool reports mhash, miner reports mhash,
However, Forager reports ghash.

Forager version 19.01.1

**Comment by yuzi-co** [comment]
for which algos?
MTP/ProgPOW and Ethash?

**Comment by toshkov02** [comment]
МТР

**Comment by yuzi-co** [comment]
should be fixed in 2cf566aa2c9d624d6468eb1b484e9cac6acc13e7
can you please verify?

**Comment by toshkov02** [comment]
MTP - OK.
Ethash - not OK, speed incorrectly

**Comment by yuzi-co** [comment]
ok, i'll post a fix soon
have you tested ProgPOW?

**Comment by toshkov02** [comment]
No. I do not use pools with ProgPOW

**Comment by yuzi-co** [comment]
fix in e8e1bf9ed2737c9c6d65fa5bd89936c4612203ae
