### ISSUE TITLE
Equihash150 (Beam) on Nicehash

### ISSUE THREAD

**Issue by toshkov02** [yuzi-co/Forager#81]
В окне N-Gminer-1.24 на алгоритме Equihash150|4gb в пуле NiceHash пишется ошибка:
Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
Но Forager считает, что всё хорошо и хэши учитывает.

**Comment by toshkov02** [comment]
N-lolMiner-0.7a4 при таком же алгоритме и пуле пишет:
Connected to beam.eu.nicehash.com:3370
Error: Handshake failed with message stream truncated
Lost connection to stratum server beam.eu.nicehash.com:3370 or server not reachable.
И бенчмарк становится бесконечным.

**Comment by toshkov02** [comment]
> В окне N-Gminer-1.24 на алгоритме Equihash150|4gb в пуле NiceHash пишется ошибка:
> Share Rejected: Invalid nonce; is miner not compatible with NiceHash?
> Но Forager считает, что всё хорошо и хэши учитывает.

Уточнение. На другой машине шары сначала принимались, а потом перестали.

**Comment by TTpartizan** [comment]
У найса протокол другой немного. Ждите обновления майнера.

**Comment by toshkov02** [comment]
> **Пока нету майнеров которые поддерживают NiceHash, советую временно добавить в конфиг:**
> 
> **Currently there are no miners supporting NiceHash Beam. I suggest temporarily add to config.ini:**
> 
> `ExcludeAlgos_NiceHash = Equihash150 `

Спасибо, я даже и не заметил, что такое исключение есть.
Cделай, пожалуйста, исключение для групп видеокарт на уровне алгоритмов майнера.
Например, сейчас ExcludeMiners_NVIDIA = N-CryptoDredgeCUDA92_0.16.1, а нужно запретить не весь майнер, а алгоритм майнера, например, N-CryptoDredgeCUDA92_0.16.1/MTP.

**Comment by yuzi-co** [comment]
New BMiner works with NiceHash (AMD/NVIDIA)
GMiner should also work, but untested (NVIDIA)

**Comment by alucard20724** [comment]
14.1 Bminer doesn't work on my AMD systems with Nicehash (i don't run on other pools).. miner just keeps closing out a few seconds after starting. 

14.1 Bminer and 1.25 Gminer works on NVIDIA systems with Nicehash (i don't run on other pools) with 1080ti/1070,

1.25 Gminer doesn't work with my 3GB 1060 system.

**Comment by alucard20724** [comment]
@yuzi-co Here's my log file.  it looks like there is an extra "3" in the port number

21:04:45.02	Info	A-Bminer-14.1/Equihash150/Equihash150 with Power Limit 0 (id 0-0) for group AMD is the best combination for device group, last was 
21:04:48.80	Debug	Started System process Id 10452 for A-Bminer-14.1/Equihash150/Equihash150 with Power Limit 0 (id 0-0) for group AMD --> C:\Users\Scott\Documents\Forager-v19.01.1 - AMD\Bin\A-Bminer-14.1\bminer-lite-v14.1.0-373029c\bminer.exe -uri beam+ssl://3BzCKogDPHfbgibPJzSh47Jbxk42CTEAv4.AMDi8700K-AMD:x@beam.usa.nicehash.com:33370 -devices amd:0,1 -max-network-failures=8 -watchdog=false -api 127.0.0.1:4028
21:04:49.02	Info	Next interval: 900
21:04:52.61	Warn	Detected miner error A-Bminer-14.1/Equihash150 (id 0-0) --> C:\Users\Scott\Documents\Forager-v19.01.1 - AMD\Bin\A-Bminer-14.1\bminer-lite-v14.1.0-373029c\bminer.exe -uri beam+ssl://3BzCKogDPHfbgibPJzSh47Jbxk42CTEAv4.AMDi8700K-AMD:x@beam.usa.nicehash.com:33370 -devices amd:0,1 -max-network-failures=8 -watchdog=false -api 127.0.0.1:4028

**Comment by yuzi-co** [comment]
this is actually correct
port 33370 and beam+ssl://
or 3370 and beam://
for me both work with AMD

try to run it manually and see if there are errors

also sometimes it rejects the shares, but i believe this is a problem with bminer and nicehash implementation

**Comment by toshkov02** [comment]
Fix: change in A-Bminer-14.1.json "-devices amd:#Devices#", -> "-devices #Devices#",

**Comment by yuzi-co** [comment]
That might work on AMD only machine, but will mine on NVIDIA devices in a mixed one

Seems that the proper way is "-devices amd:0,amd:1"
I posted a commit that should fix it

**Comment by alucard20724** [comment]
@yuzi-co your commit fixed it. it runs now.
