### ISSUE TITLE
skip does not work in case of miner error

### ISSUE THREAD

**Issue by petrovsky34** [yuzi-co/Forager#82]
I have a rig for 10 cards 2 of them 1063. 
1063 permanent error

**Comment by yuzi-co** [comment]
Which miner gives that error?
Does it continue mining on other cards?

**Comment by petrovsky34** [comment]
gminer card 1063

**Comment by petrovsky34** [comment]
4gb yes 1050ti beam work
3gb no 1060 3gb beam not work

**Comment by petrovsky34** [comment]
before pass worked now there is no

**Comment by petrovsky34** [comment]
beam algo

**Comment by yuzi-co** [comment]
There is a problem with Windows 10 that it uses some memory for itself.
Pushed a fix to set beam work only with 4gb.

**Comment by petrovsky34** [comment]
winвows 7 ??? 
windows 8 ???

**Comment by yuzi-co** [comment]
Win 7 should be able to mine with 3gb, not sure about 8
If you use it, you can change the miner file manually until miner developer can work around it

**Comment by petrovsky34** [comment]
Ok

вс, 3 Фев 2019, 17:41 yuzi-co notifications@github.com:

**Comment by petrovsky34** [comment]
work beam windows 7 3gb 1063
