### ISSUE TITLE
GrinPro-1.1 does not download

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#84]
A-GrinPro-1.1 does not download the miner for AMD... or is it just me.  I wanted to run cuckaroo29 and my AMD systems for nicehash.

doesn't download for nvidia systems either.

gminer 1.30 downloads fine and runs fine on nvidia systems on nicehash.

**Comment by yuzi-co** [comment]
Sadly GrinPro doesn't work with NiceHash
That may be the reason it doesn't even download. But I have mirror the download just in case to github
