### ISSUE TITLE
Gminer 1.31 with grin31 support

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#85]
Gminer 1.31 with grin31 support

**Comment by alucard20724** [comment]
cuckatoo31 not displaying, nor recording hashrate in forager.  forager is just showing 0 h.

gminer 1.31 and nicehash shows that i'm mining 0.65 G/s for 1080ti, which should show up as 0.6 h on forager, as cuckaroo29 shows up as 7 G/s on gminer which is 7h on forager.

**Comment by yuzi-co** [comment]
G/s = Graphs/s
like Sol/s for Equihash
which both are like Hash/s

its not Gigahash )

**Comment by alucard20724** [comment]
i'm just posting what is displayed in the miner window.  i didn't say gigahash.  what i posted are what the miner reports and what nicehash reports.
Both gminer and nicehash reports G/s...... not GH/s nor Ghash/s

**Comment by yuzi-co** [comment]
I understand.
Basically it's Graphs. which is like Solutions for Equihash and Hashes for all others.
Forager is displaying all of them as h/s for simplicity.

**Comment by alucard20724** [comment]
forager needs to be adjusted to show less than 1 G/s, which is less than 1 h/s, otherwise cuckatoo31 and other miners of similar speeds will not work with forager.

maybe changing forager to show 0.0 h/s or 0.00 h/s

**Comment by yuzi-co** [comment]
The numbers from the API are saved in decimal format and displayed with 4 digit precision.
Can you verify what do you see in the API when the miner is running?
try http://127.0.0.1:4068/stat and post here

**Comment by alucard20724** [comment]
{"uptime":611,"server":"stratum://grincuckatoo31.usa.nicehash.com:3372","user": "itsasecret-NVIDIA","algorithm":"Cuckatoo 31 \"Grin\"","electricity":0.032,"total_accepted_shares":2,"total_rejected_shares":0,"devices":[{"gpu_id":0,"bus_id":"0000:01:00.0","name":"MSI GeForce GTX 1080 Ti 11GB","speed":0.60,"accepted_shares":2,"rejected_shares":0,"temperature":62,"temperature_limit":90,"power_usage":192}],"speedRatePrecision":2,"speedUnit":"G/s","powerUnit":"G/W"}

**Comment by yuzi-co** [comment]
So speed is reported as "speed":0.60, this is exactly what Forager records

**Comment by alucard20724** [comment]
during benchmarking, it's displaying 0 and never finishing the benchmark.

**Comment by alucard20724** [comment]
![image](https://user-images.githubusercontent.com/28934670/52640400-0549a880-2e9c-11e9-8b6d-673e6dd50174.png)

**Comment by alucard20724** [comment]
![image 1](https://user-images.githubusercontent.com/28934670/52641687-092afa00-2e9f-11e9-8944-37f19c502e95.png)

**Comment by alucard20724** [comment]
it looks like the HashRate file is never being created because the LocalSpeed is being displayed as "0 h".

**Comment by yuzi-co** [comment]
Seems so, and I fail to understand why it doesn't detect the hashrate.
There should be no problem reading and recording any decimal number, no matter how small

Assuming the miner is reporting the hashrate, I would say that maybe the APi request fails, but I that you have benchmarks for Cuckaroo29 for the same miner, so it should work... Can you try setting in config.ini
ForceDynamicPorts = Enabled

**Comment by alucard20724** [comment]
i did the ForceDynamicPorts = Enabled in config.ini and restarted forager.  same results.

maybe changing the localSpeed to display 0.0 h instead of 0 h could possibly fix

**Comment by yuzi-co** [comment]
The display is automatically formatted. If it shows 0 h, then it didn't detect speed for some reason

**Comment by alucard20724** [comment]
I recommend doing a version release to 19.02.   I just noticed that version 19.01.1 does not have the "Gminer" api in the include.ini file.   Didn't notice this before because all the version of gminer work without the "gminer" api.
I'd rather work with a baseline rather than an ever changing master file

**Comment by yuzi-co** [comment]
I wasn't planning to post a release until I finish a big rewrite that I am working on, but there you are :)

**Comment by alucard20724** [comment]
thanks... once i get time to play with it, hopefully it will resolve the problem.  

I'm starting to suspect that there may be issues with gminer api,  when i added the gminer api to the include.ini file, then by invidia system wouldn't display the hashrate for cuckaroo29 in forager, however when i removed it, forager would display the hashrate for cuckaroo29.  regardless of either setup, neither would display the hashrate in forager from cuckatoo31..
This is why i'm starting to suspect the gminer api.

**Comment by alucard20724** [comment]
@yuzi-co it works with version 19.02.. so i'm closing this out.

**Comment by alucard20724** [comment]
@yuzi-co it works with version 19.02.. so i'm closing this out.
