### ISSUE TITLE
A-lolMiner-0.7a5.json doesn't work with vega cards on nicehash

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#86]
works fine with rx580/570/560/480/470
i only use nicehash
here's my log file from vega system

02:21.75	Warn	Detected more than 3 fails, cancelling combination for A-lolMiner-0.7a5/Equihash150/Equihash150 with Power Limit 0 (id 208-0) for group AMD
00:02:21.75	Info	A-lolMiner-0.7a5/Equihash150/Equihash150 with Power Limit 0 (id 208-0) for group AMD is the best combination for device group, last was A-lolMiner-0.7a5/Equihash150/Equihash150 with Power Limit 0 (id 208-0) for group AMD
00:02:21.75	Info	Killing in 0 sec. A-lolMiner-0.7a5/Equihash150/Equihash150 with Power Limit 0 (id 208-0) for group AMD with system process id 14740
00:02:22.86	Debug	Started System process Id 7876 for A-lolMiner-0.7a5/Equihash150/Equihash150 with Power Limit 0 (id 208-0) for group AMD --> C:\Users\Scott\Documents\Forager-v19.01.1 - AMD\Bin\A-lolMiner-0.7a5\lolMiner.exe --pool beam.usa.nicehash.com --port 33370 --user notgoingtotellyou.AMDi8700K-AMD --pass x --devices 0,1 --apiport 4028 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --tls 1 --coin BEAM
00:02:22.87	Info	Next interval: 900
00:02:40.32	Warn	Detected miner error A-lolMiner-0.7a5/Equihash150 (id 208-0) --> C:\Users\Scott\Documents\Forager-v19.01.1 - AMD\Bin\A-lolMiner-0.7a5\lolMiner.exe --pool beam.usa.nicehash.com --port 33370 --user notgoingtotellyou.AMDi8700K-AMD --pass x --devices 0,1 --apiport 4028 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --tls 1 --coin BEAM
00:02:44.43

**Comment by yuzi-co** [comment]
try to run the miner manually with the command you see in the log, and see if there are any errors
`lolMiner.exe --pool beam.usa.nicehash.com --port 33370 --user notgoingtotellyou.AMDi8700K-AMD --pass x --devices 0,1 --apiport 4028 --digits 2 --longstats 60 --shortstats 5 --connectattempts 3 --tls 1 --coin BEAM`

If there is an error in the miner - please post it here
Also, are there are NVIDIA devices in the same rig? Integrated video?
Full log would be very useful (you can remove the wallets/usernames/api keys)

**Comment by alucard20724** [comment]
@yuzi-co this works with version 19.02.1

**Comment by yuzi-co** [comment]
great
so i can close it? :)

**Comment by alucard20724** [comment]
yes... close it
