### ISSUE TITLE
Xmrig 2.12.2-beta NVIDIA - failing - (TRTL)

### ISSUE THREAD

**Issue by pstarSR** [yuzi-co/Forager#87]
Xmrig 2.12.2-beta NVIDIA is failing/error out ( for TRTL aka turtlecoin ). at start of miner ( forager v19.02.1 ), I checked with a fresh install of xmrig 2.12.2-beta on my machine alone and it connected and mined fine.

I was looking to find the variant on the error output but its not visible in the error output. 

Other cryptonight algos mine fine with this miner in Forager. its just turtle thats having an issue

*** note, I run the CPU miner option also, and noticed when the miner started to fail you have a monitor that counts failures and adjusts/skips the miner. ( hard to read it flashes by very quickly on the output ) What I noticed is that it wont actually skip it, even though I was using CPU to mine, that miner ( JCP ) was fine. but the miner ( forager ) would try to skip the CPU miner, not the failing nvidia miner. so I disabled CPU mining, reran it. It registered the failure and said it would skip the miner, but it never did. it got stuck in a loop of trying the same miner and failing 

-- added Start-Sleep -Seconds 10 script to Core after certain output to read. 

*** forced a command line version of the same miner ( xmrigCUDA91-2.12 ) with the command line that forager is forcing. this is the error it reproduced

" [CUDA] Error gpu 0: <cryptonight_core_gpu_hash>:718 "invalid configuration argument"

--- looking at the CL from xmrig its showing its cuda configuration as
PCI:0000:01:00 GeForce GTX 970 @ 1342/3505 MHz 172x39 6x25 arch:52 smx:13

seems the "Blocks" setting is off

--- Looking at the CL from xmrig (standalone ) -  runs and mines fine

blocks are set to 1342/3505 64x39 6x25 arch:52 smx:13

**** as far as I can tell "#AlgorithmParameters#" is calculating something incorrectly. I remove this portion of code in the miner JSON and it will connect, but fail as the algo isnt set anymore ( defaults to auto, and returns bad shares ). I have been scouring the PS1 files, searching for this tag and where its being defined, so far I have come up empty handed. Somewhere the cuda block/ threads are being set, and this is where the error stems from. but for the life of me, searching all the code I cant find where that "#AlgorithmParameters#" is defined. I see its changed from "#AlgorithmParameters#" = $Algo.name in the core. PS1 file. what gets my head scratching is these miners will mine other cryptonight coins fine, only turtle is causing this issue, somewhere the code for the Algo is tweaking the cuda block/threads differently than the other Algos. 

**** updated to new git files v19.03 ****
no change
more failures on cryptodredge for cnv8, seems like the same block/thread problem causing the gpu to fail

**Comment by yuzi-co** [comment]
> but the miner ( forager ) would try to skip the CPU miner, not the failing nvidia miner

Showing the other miner is just a display issue, fixed in 0adcc445d7b431a311a54e006ea6d5b635bc6654.
Miner should be marked as failed after 3 failures, and, it should be skipping Miner/Algo/Pool combination. So it may try with a different pool.

> as far as I can tell "#AlgorithmParameters#" is calculating something incorrectly

#AlgorithmParameters# is simply replaced by the "-a cn/gpu" ($Algo.Value) part for CnGpu. No special magic, no block settings. 

Try leaving only the XMRig for your CUDA version (Forager assumes lower CUDA miner versions are compatible with higher CUDA drivers. I probably need to change that).

Try mining with N-XMR-Stak (from Additional Miners folder)

Maybe something else is interfering... Try setting both
Afterburner = Disabled
HardwareMonitoring = Disabled
just for the test

**Comment by pstarSR** [comment]
Afterburner off
Hardware monitor off
10.0 Cuda version xmrig only
------ failed ------- same error, same block of 176x39

XMR-stak test
---- failed on Masari - cnHalf - error 256 ---  checked the config file created for xmrstak
"gpu_threads_conf" :
[
  // gpu: GeForce GTX 970 architecture: 52
  //      memory: 3884/4096 MiB
  //      smx: 13
  { "index" : 0,
    "threads" : 4, "blocks" : 104,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
    "mem_mode" : 1,
  },

],
Side note, XMR-stak benchmarked fine for Graft prior to this failure, looking at the config file for Cnv8 in the xmr stak folder, the block/thread setting is identical. 

-----  ran Xmr-stak solo ( with turtle pool/algo), it created its own Nvidia.txt config. was identical to the one forager created( for MSR/GRAFT). Started miner fine, but failed shares for some reason, even though the algo is correct.  *** ignoring for now*** stak is low H/S

**************************************************
Back to xmrig-nvidia-2.12.0-beta


----- Test of CL miner code 
**** standalone miner, CL created by config.xmrig.com  - success****
xmrig-nvidia.exe -a cryptonight-pico --donate-level 1 -o turtle.miner.rocks:5555 -u TRTLv21r6yoHRaQphGtHcFKjmLxxGzgty3kTE8iomWbFeSecPntvko34pkgB8WFVRxgVoJxTtH6dd2VdCSufGpdFbEbgD1ce5YF -p rig=SuperRig


**** forager created CL code - Fail ****
xmrig-nvidia.exe -o stratum+tcp://turtle.miner.rocks:5551 -u TRTLv21r6yoHRaQphGtHcFKjmLxxGzgty3kTE8iomWbFeSecPntvko34pkgB8WFVRxgVoJxTtH6dd2VdCSufGpdFbEbgD1ce5YF -p w=Sethsuperrig-Pc_NVIDIA --cuda-devices=0  --donate-level 1 --api-port 4068 -a cn-pico/trtl

*****************************************************

I figured it out, It looks like the extra data in the miner config file being populated was causing it to freak out.
(176x39 6x25 arch:52 smx:13)
originally the miner config populates Nicehash info, and cuda-devices

    "Arguments": [
        "-o #Protocol#://#Server#:#Port#",
        "-u #Login#",
        "-p #Password#",
        "--cuda-devices=#Devices#",
        "$(if ($Nicehash){'--nicehash'})",
        "--donate-level 1",
        "--api-port #APIPort#",
        "#AlgorithmParameters#"
    ],

If you remove those arguments -  miner connects, blocks/threads are correct now, and shares are accepted.
(64x39 6x25 arch:52 smx:13)


    "Arguments": [
        "-o #Protocol#://#Server#:#Port#",
        "-u #Login#",
        "-p #Password#",
        "--donate-level 1",
        "--api-port #APIPort#",
        "#AlgorithmParameters#"
    ],
**************************************************************

with the above 6 arguments only, in all the xmrig miners config.json ( cuda 91, 92, 10 ) miner is good to go, forager registers H/s, profitability and watts.

turned back on -
HardwareMonitor
CPU mining

still off -
Afterburner
