### ISSUE TITLE
Potential MTP on nicehash

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#88]
FYI.  MTP is popping up on nicehash.
https://www.nicehash.com/marketplace/mtp

currently everything is failing benchmarks... i'm assuming this is because nicehash is working out the bugs on their side.

**Comment by yuzi-co** [comment]
probably custom stuff in the stratum, as usual for them...

**Comment by yuzi-co** [comment]
disabled all mtp miners for NH for now.
when support is added, will enable

**Comment by alucard20724** [comment]
@yuzi-co  trailingstop has a beta version with tt-miner that works with nicehash... it hasn't been officially released yet.  I'm playing with the beta now.

**Comment by alucard20724** [comment]
@yuzi-co Nicehash has a version that works with nicehash.
https://github.com/nicehash/NiceHashMinerLegacy/releases
it's in the bin_1_9_0_15.zip, in a folder called ccminer-mtp
