### ISSUE TITLE
lyclminer 0.2.1 which has support for vegaVII

### ISSUE THREAD

**Issue by alucard20724** [yuzi-co/Forager#93]
4% faster over previous version for gfx9 cards

works for vegaVII cards

https://github.com/CryptoGraphics/lyclMiner

**Comment by yuzi-co** [comment]
is it faster than TeamRed?

**Comment by alucard20724** [comment]
I'm going to say yes, because TeamRed currently does not support the Vega VII cards.  TeamRed does not run on the Vega VII cards.  WildRigMulti 0.15.3.8 gets @100 Mh for Lyra2v3 for Vega VII card.  Stock settings.

**Comment by alucard20724** [comment]
@yuzi-co lyclminer gives me @103Mh for version 0.2.1 for Vega VII

**Comment by yuzi-co** [comment]
3% over wildrig, definitely an improvement :)
You can try increasing the WorkSize and see if that helps even more

**Comment by alucard20724** [comment]
I've already tried changing the worksize, but it didn't appear to change anything.  i might just be to tired at this point.. it's well past my bed time and in need to get up in a few hours for regular job... that keeps getting in the way of mining o_0
