### ISSUE TITLE
Sometimes miner window does not refresh

### ISSUE THREAD

**Issue by DrRobotto** [yuzi-co/Forager#96]
Sometimes the miner window does not refresh on my mini rig and therefore there is no autoswitching anymore. Unfortunately I can not reproduce the error, it occurs from time to time.

Keep up the good work!

**Comment by yuzi-co** [comment]
Its probably a Windows issue with Quick Edit.
When you click in the Forager window, it selects something and prevents from Forager fro updating.

There is nothing I can do about it.
The only recommendation is to disable Quick Edit in the Properties menu of the cmd console

**Comment by DrRobotto** [comment]
Hm, but even after some time when I am not at the computer?

**Comment by yuzi-co** [comment]
Shouldn't be. But a single click with a mouse on the window can be enough, which can happen by mistake.
If it happens, try to see if any part on the screen is selected and if pressing any key in the console fixes it.

**Comment by DrRobotto** [comment]
Normally it fixes the issue, but not in this case ... I have to restart the miner window

**Comment by DrRobotto** [comment]
Now I try to diasble the quick edit option and report back if it happens again

**Comment by DrRobotto** [comment]
Did not change anything. Same behaviour. I will write a small watchdog script which restarts the miner if there is no status report

**Comment by DrRobotto** [comment]
I think I found the issue: I removed the api call to MinerStatusUrl and it did not occur again ... maybe the service does not respond to the request and therefore the script waits for it?

**Comment by yuzi-co** [comment]
I will make sure it runs asynchronously
Thank you for the catch

**Comment by yuzi-co** [comment]
report is now async, so it should solve this issue
