### ISSUE TITLE
Hive Os Work??? Yes, it does! ;)

### ISSUE THREAD

**Issue by petrovsky34** [yuzi-co/Forager#98]

**Comment by yuzi-co** [comment]
Untested, but probably yes

I will hopefully have time to test it during the week

**Comment by petrovsky34** [comment]
Well I look forward to))) and write how to connect to HiveOS

**Comment by yuzi-co** [comment]
Check which Ubuntu version is your HiveOS running (cat /etc/os-release)

Get latest relevant Powershell .deb package from https://github.com/PowerShell/PowerShell/releases 
```
# note the ubuntu version
wget https://github.com/PowerShell/PowerShell/releases/download/v6.2.0/powershell_6.2.0-1.ubuntu.16.04_amd64.deb

# install powershell package
dpkg -i powershell_6.2.0-1.ubuntu.16.04_amd64.deb

# install powershell dependecies
apt install -f

# get Forager
git clone https://github.com/yuzi-co/Forager
```
Setup Config.ini and use start.sh for menu or edit autorun.sh to setup your pools, similar to Windows

Profit :)

There are probably some issues, I will be looking into it
Not using any HiveOS specific features, but its a quick way to set up linux on your mining rig :)
